name: Android
on: [push, pull_request]

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.0
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest
      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Restore Previous Cache
        if: ${{ always() }}
        id: cache-debug-build-android-restore
        uses: actions/cache/restore@main
        with:
          path: |
            ~/haxelib
            ~/.gradle
            export/release/android/haxe
            export/release/android/obj
          key: cache-android-build
      - name: Install Haxe Libraries
        run: |
          haxelib setup C:/haxelib
          haxelib install hmm --quiet
          haxelib run hmm install
        shell: cmd
      - name: Configure Android
        run: |
          haxelib run openfl setup -alias -y
          haxelib run openfl config ANDROID_SDK $ANDROID_HOME
          haxelib run openfl config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run openfl config JAVA_HOME $JAVA_HOME
          haxelib run openfl config ANDROID_SETUP true
      - name: Compile
        run: haxelib run openfl build android
        env:
          cert_pass: nullfunni
          cert_alias_pass: nullfunni
      - name: Clear Previous Cache
        if: ${{ always() }}
        uses: actions/github-script@main
        with:
          script: |
            try {
              const caches = await github.rest.actions.getActionsCacheList({
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
              if (typeof caches.data.actions_caches != null && caches.data.actions_caches.length > 0) {
                for (const cache of caches.data.actions_caches) {
                  if (cache.key == "cache-android-build") {
                    console.log('Clearing ' + cache.key + '...')
                    await github.rest.actions.deleteActionsCacheById({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      cache_id: cache.id,
                    })
                    console.log("Previous Cache Cleared!")
                  }
                }
              }
            } catch (error) {
              console.log(error.message);
            }
      - name: Save Current Cache
        if: ${{ always() }}
        id: cache-release-build-android-save
        uses: actions/cache/save@main
        with:
          path: |
            ~/haxelib
            ~/.gradle
            export/release/android/haxe
            export/release/android/obj
          key: cache-android-build
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Android Build
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
