name: MacOS
on: [push, pull_request]

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      - name: Install Haxe Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hmm --quiet
          haxelib run hmm install
      - name: Compile
        run: haxelib run openfl build mac
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: MacOS Build
          path: export/release/macos/bin
